name: Setup Node
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v5
      with:
        node-version-file: .node-version
        cache: pnpm
    - run: cp ./.env.sample ./.env
      shell: bash
    - run: npm run setup
      shell: bash
    - run: pnpm i && pnpm rebuild
      shell: bash
    - run: pnpm generate:client
      shell: bash
